### ISSUE TITLE
unit test for ID columns

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugphyzz#107]
## Unit test @sdgamboa 

Require: 
* `NCBI_ID`

Allow optionally:
* `.+_ID` (regex, anything ending in `_ID`)

## Curation  @BenNachod 

(Change Accession_number to Accession_ID)

**Comment by sdgamboa** [comment]
There aren't that many extra ID columns. I added them to the template file, so the
columns can be documented and tested as well.
