### ISSUE TITLE
Create unit tests for fattyAcidComposition function

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#115]
Create a unit test for the fattyAcidComposition function and the customLinks function.
Link to the R file: https://github.com/waldronlab/bugphyzz/blob/main/R/fattyAcidComposition.R

**Comment by kbeckenrode** [comment]
Where is this issue? @sdgamboa

**Comment by sdgamboa** [comment]
This unit test was not created. I can take a look into it. I was wondering if this function could be integrated somehow into the physiologies function. It seems to me that the data model is the same as the other datasets (the only difference is the preprocessing with tidyr?).
