### ISSUE TITLE
Convert functions to scripts

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#116]
@lwaldron, @JonathanYe3, @jwokaty Should the functions defined in https://github.com/waldronlab/bugphyzz/blob/main/R/bergeys_textmine_functions.R and 
https://github.com/waldronlab/bugphyzz/blob/main/R/bergeysAbstracts.R be moved to a runnable script for curation under the inst/scripts directory?

**Comment by kbeckenrode** [comment]
Have the functions been converted to scripts?

**Comment by JonathanYe3** [comment]
Oh I don't think these should be converted, the web scraper was used once to scrape bergey's and I'm not sure if any bugphyzz users would need it

**Comment by sdgamboa** [comment]
It seems that these functions are part of how bergeys abstracts were processed and the spreadsheet generated. So they belong as part of [bugphyzzWrangling](https://github.com/waldronlab/bugphyzzWrangling). Please write reproducible documentation there using these functions, @JonathanYe3.

I moved the functions to inst/scripts/.

I'll open a new issue there. Closing this issue.
