### ISSUE TITLE
Correct the class of the Parent_NCBI_ID column

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#131]
The Parent_NCBI_ID column is of type "character" when is added to the datasets imported by bugphyzz, but it should be of type "integer". This taxonomy information is precomputed with the 
https://github.com/waldronlab/bugphyzz/blob/main/data-raw/sysdata.R file.

The data-raw/sysdata.R file must be updated to make sure that the Parent_NCBI_ID column is of integer type.

**Comment by lwaldron** [comment]
This sounds like a bug, not an invalid issue.

**Comment by sdgamboa** [comment]
This has been corrected ([code](https://github.com/waldronlab/bugphyzz/blob/91ca165093aabc0be27c4653abac4cc926566a9a/data-raw/sysdata.R#L82-L86)). Closing this issue.

``` r
suppressMessages({
    library(bugphyzz)
    library(purrr)
    phys <- physiologies()
})

all(map_lgl(phys, ~ is.integer(.x$Parent_NCBI_ID)))
#> [1] TRUE
```

<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
