### ISSUE TITLE
Document columns in datasets

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#132]
Add documentation for Columns and their values.

**Comment by kbeckenrode** [comment]
Where would be the best place to add this documentation? I believe @sdgamboa you started a table here: [https://docs.google.com/spreadsheets/d/1Jfqzy1Atf6Fk89eZuPIF7tqd04gDc9UkEHq8aeeX2bE/edit#gid=2049314625](https://docs.google.com/spreadsheets/d/1Jfqzy1Atf6Fk89eZuPIF7tqd04gDc9UkEHq8aeeX2bE/edit#gid=2049314625)

Where else should this information live besides a Google Doc?
