### ISSUE TITLE
Resolve different sources for the same attribute and microbe

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#147]
Find duplicate entries in each dataset with conflicting attributes and sources. Create a default behavior. Concatenate when sources are different but they don’t disagree. For example, a bacteria found in two different places

**Comment by kbeckenrode** [comment]
I believe we have a duplicate issue (ironic) of this? Now that we have a confidence interval of sources, that should help with ranking duplicate or disagreeing attributes.

**Comment by sdgamboa** [comment]
I noticed that the classification is based on high, medium, and low ([table](https://docs.google.com/spreadsheets/d/18PH_Ukec-yU-S0_yGI9UWoAqyfcxdR6jdLN4s1bDa1k/edit#gid=0)).  I haven't encountered this scenario  yet, but how to resolve if the two attribute sources are labeled as 'medium' (for example)? Maybe a ranking or order of preference would work? I added this to the agenda for discussion.
