### ISSUE TITLE
Doubts/notes about the attributes file

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#153]
@kbeckenrode

Some questions/notes regarding the attributes file: https://github.com/waldronlab/bugphyzz/blob/main/inst/extdata/attributes.tsv

+ Some ontology terms are separated by an underscore (_) while others are separated by a colon (:). Is this correct? Do they come from different sources?

+ What is the source of these ontology terms? I think it would be good adding the source of the ontology terms in this table if they come from different sources.

+ Are the ontology values of facultatively anaerobic (MICRO_0000504) and obligately anaerobic (MICRO:0000504) correct? They have the same prefix and number, they only change because one has an underscore and the other has a colon as a separator.

+ The ontologies OMIT:0027643 and OMIT_0006994 don't have a description.

**Comment by kbeckenrode** [comment]
That must've been a curation issue on my end. Sorry about that they should all be colons (:). They all come from the same source. Google Ontology Lookup Service, and you'll see hundreds of different kinds of ontologies

**Comment by kbeckenrode** [comment]
We actually just talked about this on slack. I think we will need to make a function to convert these. Sorry about that.
