### ISSUE TITLE
Separating data Attribute column

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#156]
[ProTraits data](https://docs.google.com/spreadsheets/d/1KvySjXtRNTTT8kEA28OlMv00rMpe_nsxJ4C3cxJgWdM/edit#gid=0
)
Column E (Attributes) has the attribute and the attribute value is connected through an equal sign. This column needs to be parsed. I'm looking at you @JonathanYe3

**Comment by JonathanYe3** [comment]
I finished parsing the ProTratis sheet - data can be found in https://docs.google.com/spreadsheets/d/1IrEi8P4WJbngtzzmu_ty0zBehP64Q8QLwR7W_o-uYLY/edit#gid=1036936281

**Comment by JonathanYe3** [comment]
I will start adding these data to the original attribute spreadsheets, but wanted to give anyone an opportunity to check for possible errors/modifications.

**Comment by sdgamboa** [comment]
So far the columns Rank, Parent_rank, Parent_NCBI, and Parent_name are joined to the datasets from a taxonomy table crated with the script in data-raw: https://github.com/waldronlab/bugphyzz/blob/main/data-raw/sysdata.R

Not sure if this will continue to be the way of adding parent and rank info for the taxa, or if it's better to have everything in the spreadsheet.

I just mention this to take into account that the other spreadsheets don't have rank and parent columns. If these columns are added, the rank and parent columns will be duplicated, e.g., Rank.x and Rank.y. This might be relevant when importing the spreadsheets.

**Comment by sdgamboa** [comment]
I thnk confidence_interval is now frequency.

**Comment by JonathanYe3** [comment]
Ah yes, I will make sure not to add new columns and change confidence interval to frequency. The original Protratis sheet was a little outdated, so some adjustments are necessary.
