### ISSUE TITLE
Habitat spreadsheet needs NCBI IDs

### ISSUE THREAD

**Issue by JonathanYe3** [waldronlab/bugphyzz#159]
I recently fixed some of the habitat spreadsheet's taxon name entries, and added a MiDAS ID column. 
[habitat2](https://docs.google.com/spreadsheets/d/1PpZ56km1XJ7Dk9KOFtDTPzJ62n6AoiZ3ABgac-_4Ags/edit#gid=888586110)

There are still many missing NCBI IDs, which could be filled using the Genome and Accession IDs. I had some trouble getting @sdgamboa's code to accomplish this task, which uses Entrez's efetch to work.

**Comment by sdgamboa** [comment]
Thanks, @JonathanYe3! I had some work on this. I'll add the data. Related to #103.

**Comment by kbeckenrode** [comment]
@JonathanYe3 it looks like half of habitat2 has the NCBI IDs. It seems the MIDAS ones do not have IDs? Thanks for doing this.

**Comment by JonathanYe3** [comment]
@kbeckenrode Ah yea! I totally forgot about this. I couldn't get the NCBI IDs from MIDAS to work, but @sdgamboa planned to add the data sometime.

**Comment by sdgamboa** [comment]
This has been completed. See: #226
