### ISSUE TITLE
Error in sql_integer_list

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzz#161]
When updating the pkgdown action, I got the following error when running `pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)`:

```
All NCBI ids are valid.
Quitting from lines 140-149 (checks.Rmd) 
Error in sql_integer_list(x) : 
  Found non-integer where integer required in SQL input
--------------------------------------------------------------------------------
Error in !trace_length(trace) : invalid argument type
Calls: <Anonymous> ... signal_abort -> cnd_message -> format_onerror_backtrace
Execution halted
Error: Process completed with exit code 1.
```

You can see the action at https://github.com/waldronlab/bugphyzz/runs/7421031035?check_suite_focus=true#step:8:452.

**Comment by sdgamboa** [comment]
@jwokaty, I think this has been solved, I'm not having any more errors in the vignettes (tried both in my laptop and supermicro). Can I merge this PR #160 ?

**Comment by jwokaty** [comment]
@sdgamboa Yes, please merge. The github action should run. If it still has an error, I'll reopen the issue. Thank you!
