### ISSUE TITLE
Document data model

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#162]
Formalize the bugphyzz data model, like curatedMetagenomicData at https://github.com/Ethan-Loo/Bioinformatics_Data_Curation_Collaboration/blob/main/Waldron_Lab_Curated_Schema.yaml.

In the meantime at least unmissable documentation of the data model in our GitHub repo. This should be a top priority to formalize and make self-documented the bugphyzz data model (https://github.com/waldronlab/bugphyzz/blob/main/inst/extdata/template.tsv)

**Comment by kbeckenrode** [comment]
@sdgamboa so, when I compare these two links, it seems that the first one has all the terms and descriptions of each terms that could be in a slot. How would that look like in our model? Thanks!

**Comment by sdgamboa** [comment]
Some updates were added today #173 
There are still some blanks to fill in. @sdgamboa, @kbeckenrode.
I'll open a new branch when I add some more edits.
