### ISSUE TITLE
Add attribute type to spreadsheets

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#165]
Add a column to the data model indicating the type of the attribute value.

@seandavi, is this what you had in mind for adding attribute value type?

Example of a discrete value:

| NCBI_ID | Taxon_name | Attribute | Attribute_value | Attribute_type |
| ------- | ---------- | --------- | --------------- | ---------------|
| 561 | Escherichia | facultative anaerobic | TRUE | logical |
| 838 | Prevotella | anaerobic | TRUE | logical |

Example of a numeric value:

| NCBI_ID | Taxon_name | Attribute | Attribute_value | Attribute_type |
| ------- | ---------- | --------- | --------------- | ---------------|
| 561 | Escherichia | growth temperature | 37 | numeric |
| 838 | Prevotella | growth temperature | 37 | numeric |

Possibly other types of values? numeric range?

**Comment by seandavi** [comment]
Yes. There could also be additional types besides base R types (eg., numeric range, ontology term) as needed.

**Comment by sdgamboa** [comment]
Closing. See #195
