### ISSUE TITLE
Write Physiology Sets needs update?

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzz#174]
During a meeting with @lwaldron, we noticed https://github.com/waldronlab/bugphyzz/blob/main/vignettes/articles/write_physiology_sets.Rmd, which is using `bergeys <- bugphyzz:::.bergeysAbstracts()`, which is supposed to be a hidden function. Maybe this was left as a placemarker? Not sure if this is documented in another issue.

**Comment by sdgamboa** [comment]
@JonathanYe3, it seems that this function is not meant to be used by a regular bugphyzz user, but by developers/curators. Is this correct? If so, I'll delete this vignette.

**Comment by JonathanYe3** [comment]
@sdgamboa Yup, this function is pretty much just for documentation now and there isn't really any use for it since it just returns the abstracts from Bergey's manual. We have all the curated data from these abstracts within physiologies now.
