### ISSUE TITLE
buphyzz signatures

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzz#177]
@lwaldron explained how to do some signature files for bugphyzz but suggested I ask for suggestions for some sensible groupings for a few physiologies that had numerical or range data. Could I ask for your suggestions for sensible grouping on the following:

Numerical attribute values (check off when resolved)
- [x] acetate producing
- [x] coding gene
- [x] genome size
- [x] growth temperature
- [x] length
- [x] mutation rate per site generation
- [x] mutation rates per site per year 
- [x] optimal ph
- [x] width

Varied data - how should we group?
- [x] isolation site

Numerical attribute values + missing attribute values or NAs
- [x] Butyrate-Producing Bacteria (numerical attribute values + missing attribute values)
- [x] lactate producing (numerical attribute values with NAs)
- [ ] adjusted width and length (attribute is 'length' but has an attribute_value_min and attribute_value_max)
- [x] hydrogen gas producing (numerical attribute values with NAs)

I noticed that antimicrobial sensitivity, fatty acid, and sphingolipid producing would all be one row of taxa since the attribute values are all the same. Is this okay?

**Comment by kbeckenrode** [comment]
@jwokaty I'm going through the list now for general errors, but you were asking about grouping and I don't understand what this means? Would you be able to elaborate?

**Comment by jwokaty** [comment]
For the signatures, I want to group "like" taxa together.

For example, if I look at animal pathogen, I can easily group all the "animal pathogen == TRUE" taxon names and I can also group the "animal pathogen == FALSE" taxon names. These will become the "rows" in the .gmt files, which are the signatures (if I understand correctly). Another easy example, is cell arrangement. I can group all the taxa where the attribute == single and attribute value == TRUE. I would do this for all the unique values in the cell arrangement spreadsheet.

This is not so easy to do where the attribute value is numerical or contains a range, so @lwaldron  suggested I ask you for sensible groupings for these other physiologies that may make sense to someone who is more knowledgeable about this data than myself.

**Comment by kbeckenrode** [comment]
Ah ha ok. Thank you for explaining it so clearly. Let me think about it and I'll hopefully think of reasonable groupings by the end of the day.

**Comment by kbeckenrode** [comment]
So, for isolation site, I know the data is extremely specific and varied--as you noted. Is it possible to do a keyword search and group keywords together? @jwokaty

**Comment by jwokaty** [comment]
@kbeckenrode I can try to do that for `isolation site`. I'm not sure what it will look like, but that's what i was going to try.

**Comment by lwaldron** [comment]
Great @kbeckenrode - if there are any for which there are no good _a priori_ thresholds, we could set them based on the data (e.g. quartiles, or if appears to be modes in a histogram, using kmeans-clustering)

**Comment by jwokaty** [comment]
Adding https://docs.google.com/spreadsheets/d/1MM7unEZzwfjllFGzFScV9T1gAQxBXbu03ZmozGczKIw/edit#gid=0, which has the thresholds and names.

**Comment by jwokaty** [comment]
@kbeckenrode Could I ask you to take a look at acetate as the thresholds look incorrect?

**Comment by jwokaty** [comment]
Closing since I think this is mostly resolved
