### ISSUE TITLE
Add your TODOs into BugPhyzz project

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#180]
https://github.com/orgs/waldronlab/projects/8/views/1

Add any TO DOs to project list so we can have a more holistic view of what is to be done to reach project completion

**Comment by sdgamboa** [comment]
- [ ] I added my main tasks to the projects.

**Comment by jwokaty** [comment]
I added the big ones I could think of and helped myself to adding an extra status of "Blocked" and a Comments column.

**Comment by kbeckenrode** [comment]
Thanks @sdgamboa and @jwokaty
