### ISSUE TITLE
Restrict allowed values for an attribute

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzz#185]
From the meeting with Curtis, we should restrict the values allowed for an attribute to valid attribute values at the sheet level and in the validation checks. For example, if the attribute was gram stain, the column should be restricted to 'positive', 'negative', and 'variable' (or whatever is in our ontology) and we should also perform a check on it.

**Comment by kbeckenrode** [comment]
Ill mark this as a top priority to check that ontology terms are used appropriately. Does this mean we need to remove the "TRUE" and "FALSE"?

**Comment by lwaldron** [comment]
Which instances of TRUE and FALSE do you mean? It might make sense in some
situations. But not eg if Attribute_FALSE or Attribute_TRUE would not be
meaningful signatures. For example, gramstain_positive would be a more
meaningful signature name than gramstain-negative_FALSE. I expect we would
create signature names by concatenation of the Attribute and Attribute
Value.
-- 

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

Join the microbiome Virtual International Forum: https://microbiome-vif.org

**Comment by kbeckenrode** [comment]
Ah, nevermind. I got attribute and attribute_value switched in my mind. Only attribute_value is ever True or False.

**Comment by kbeckenrode** [comment]
Any ideas of how to deal with [disease association](https://docs.google.com/spreadsheets/d/1GqY9-TMpcIPDuWUQwXja1GB1suc4-kUOj8QytvqAMq0/edit#gid=0)? There are 446 entries and nearly each one has a different attribute. It's interesting information, but may not make for interesting signatures.

**Comment by kbeckenrode** [comment]
Finished, except with a few exceptions

- disease association
- isolation site
- BacDive
- PATRIC
- Madin et al
- ProTraits

**Comment by lwaldron** [comment]
For disease association, it looks like the Attribute should be "disease association" (or better, "disease" is term EFO:0000408 in the EFO) and the Attribute_value should be the disease translated to EFO. Currently disease association is only coded in the title of the spreadsheet, and Attribute_value is always "TRUE" which uninformative if FALSE is never used. There is some repetition of diseases, and even where there isn't I don't see that as a problem.

For isolation site, note that "sampling site" is the probably relevant EFO term (EFO:0000688) for the Attribute. I find these just by going to https://www.ebi.ac.uk/ols/ontologies/efo and searching. These isolation sites could be used as-is as Attribute_value, with an ontology listing the nearest relevant ontology term (maybe from ENVO for this?)

I know I keep harping on this but _pleeeeaaaase_ prioritize using ontologies, EFO where possible and thoughtfully selected alternatives where not. This can/should a major contribution of ours to standardize the language of different databases onto a consistent ontology. To motivate by example, using the EFO term [anthrax infection](http://www.ebi.ac.uk/efo/EFO_0000778) would allow us to create a signature that groups together all other causes of "primary bacterial infectious disease" or "gram-positive bacterial infections", shown below. It's like getting information and organization for free, even things you didn't know about when you curated. Actually, we should probably create a new column for ontology codes to formalize this and eliminate the need to look up the ontology terms later.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/639942/199109858-e6d7bba3-e0d9-4c59-9c30-efd683121b20.png">

**Comment by kbeckenrode** [comment]
This is greta Levi! Sorry to make you do digging for ontologies. I was thinking of the sheer amount of unique annotations, but you being up great points with relying ontologies to make some of these decisions. Thank you Levi for your thoughtful response.

**Comment by kbeckenrode** [comment]
- BacDive
- PATRIC
- Madin et al
- ProTraits

are the only ones to remain, and we can discuss them at our meeting today

**Comment by sdgamboa** [comment]
@jwokaty, "values at the sheet level and in the validation checks"

Just looking for some clarification about the steps to follow next with this issue:

+ Add restrictions for entering data in the spreadsheets? Is this what you mean by "sheet level"? I think this would only work for data entered manually.
+ Add restrictions when importing data through the R package.
+ Create unit tests.

**Comment by lwaldron** [comment]
> Add restrictions for entering data in the spreadsheets? Is this what you mean by "sheet level"? I think this would only work for data entered manually.

Google Sheets cell validation would be helpful for manually-curated data, as a convenience for curators to help fix issues before they have to be caught by tests in the bugphyzz package. Non-manual sources (eg BacDive) don't need to go through Google Sheets.

> Add restrictions when importing data through the R package.

Users should not be served invalid data. I would suggest some non-exported functions (starting with `.` by convention) for checking the validity of data before returning it to the user 

> Create unit tests.

* For starters, just requesting each dataset to make sure it returns without error according to the checks noted above
* check that data that have been present in the past are still there (datasets and number of data points in each dataset haven't shrunk)
* anything else that could go wrong

**Comment by sdgamboa** [comment]
Related #178

**Comment by sdgamboa** [comment]
Attributes are checked in bugphyzz exports. Users won't get invalid data when importing with `importBugphyzz'. Syntax is checked with https://github.com/waldronlab/bugphyzz/blob/devel/R/check_functions.R
