### ISSUE TITLE
Evidence column is empty in COGEM datatset.

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#188]
The Evidence column needs to be filled in the [COGEM dataset](https://docs.google.com/spreadsheets/d/19DrBFbAMGNvqf17yJ4HzuKQjJoRlMCVYTCtmyugoDjQ/edit#gid=0). I think 'unknown' is best if we do not have the information.

**Comment by kbeckenrode** [comment]
Added evidence, which is "unknown"
