### ISSUE TITLE
Curation check issue

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#190]
For the ["coding genes" attribute](https://docs.google.com/spreadsheets/d/1MVQ3o4fRYA4EOjp9mNAF0AvyQ0SzzdTMoZXruAIHmb4/edit#gid=0), the curation check is detecting all [attribute values as invalid](https://waldronlab.io/bugphyzz/articles/checks.html). I thought maybe it's because the ontology term is "genes" and not coding genes. I changed the attribute to match the ontology term, and hopefully that fixes it.

@sdgamboa

**Comment by kbeckenrode** [comment]
And again, [disease associated](https://docs.google.com/spreadsheets/d/1GqY9-TMpcIPDuWUQwXja1GB1suc4-kUOj8QytvqAMq0/edit#gid=0) is marking all entries as invalid, and I'm not sure why.

**Comment by sdgamboa** [comment]
This was solved by avoiding the conversion of all attributes (`Attribute` column) to lowercase.
