### ISSUE TITLE
Bergey's fermentation product charts

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#204]
We asked a summer intern to web scrape some fermentation tables from Bergey's into a spreadsheet.  And here is what we have : [here](https://drive.google.com/drive/folders/1ebqs9RRoOkg_gUYKMKqziI4nEd_bP2pB?usp=sharing)

I can't make much sense if it. Can you? @sdgamboa @lwaldron

**Comment by sdgamboa** [comment]
I think discussion about this could continue on issue #144. Closing.
