### ISSUE TITLE
The Microbe Directory is not "exp" Evidence

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugphyzz#206]
The Microbe Directory is based on literature review without citations, not experimental evidence. I believe there is an "author statement" type evidence code?

**Comment by kbeckenrode** [comment]
We decided to make the default "high" for signature creation.

**Comment by sdgamboa** [comment]
I think 'exp' and 'unknown' (Evidence column) should be changed to 'author statement' (or another term with an ontology?) when related to the microbe directory source.

I think the default value of high confidence for the creation of signatures was a different issue. We still need/want the microbe directory evidence.

``` r
suppressMessages({
    library(bugphyzz)
    library(purrr)
    library(dplyr)
    phys <- physiologies(full_source = FALSE)
})

map(phys, ~ {
    df <- .x[.x$Attribute_source == 'The Microbe Directory',]
    count(df, Attribute_source, Evidence, Frequency)
}) |> 
    discard(~ !nrow(.x)) |> 
    bind_rows(.id = 'spreadsheet')
#>                   spreadsheet      Attribute_source Evidence Frequency    n
#> 1             animal pathogen The Microbe Directory  unknown   unknown 1416
#> 2   antimicrobial sensitivity The Microbe Directory      exp   usually  832
#> 3             biofilm forming The Microbe Directory      exp   unknown  426
#> 4  COGEM pathogenicity rating The Microbe Directory  unknown   usually 1042
#> 5         extreme environment The Microbe Directory  unknown    always 1874
#> 6                  gram stain The Microbe Directory      exp   unknown   15
#> 7                  gram stain The Microbe Directory  unknown   unknown 2337
#> 8          growth temperature The Microbe Directory      exp   unknown 1347
#> 9                     habitat The Microbe Directory      exp   unknown 2354
#> 10                 optimal ph The Microbe Directory      exp   usually  886
#> 11        plant pathogenicity The Microbe Directory  unknown   usually 1493
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sdgamboa** [comment]
Solved with [code](https://github.com/waldronlab/bugphyzz/blob/67696685364ffb7f56fcfc2af3668de78daeb87f/R/physiologies.R#L207-L214) and [file](https://github.com/waldronlab/bugphyzz/blob/main/inst/extdata/attribute_sources.tsv).
