### ISSUE TITLE
BacDive attributes need to be curated for inclusion in attributes.tsv

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#224]
@kbeckenrode, BacDive attributes that need curation. I did some of the aerophilicity dataset.

https://docs.google.com/spreadsheets/d/1RXdCMSjhJbj-LGJjkEG9fvddjFBfpusCPOb3Aqk77_8/edit#gid=0

**Comment by kbeckenrode** [comment]
Thanks for the great list. Since it is so long, I'm not sure how to proceed. As you mentioned it seems too long to manually curated. Any ideas?

**Comment by sdgamboa** [comment]
I curated most of these attributes here: https://github.com/waldronlab/bugphyzz/blob/devel/R/bacdive.R

Some of them were excluded on purpose. They're 'commented' in the code. I think it would be worth to review these in the future. They're too many for the current propagation pipeline.
