### ISSUE TITLE
`importBugphyzz` returns a list?

### ISSUE THREAD

**Issue by shbrief** [waldronlab/bugphyzz#235]
It seems like `importBugphyzz` is returning a list instead of a data frame. Can you check this? Thanks!

**Comment by sdgamboa** [comment]
@shbrief, yeah I updated the code here: https://waldronlab.io/bugphyzz/articles/bugphyzz.html. 
Some reasons for this change are in these PRs: https://github.com/waldronlab/bugphyzz/pull/234 and 
https://github.com/waldronlab/bugphyzzExports/pull/47. Basically, the Attribute_value column can take numeric values now, hence the change (can't mix character, logical, and numeric). I updated all the code in the analyses to work with this list: 
https://github.com/waldronlab/bugphyzzAnalyses.
