### ISSUE TITLE
Can't open/find BacDive associated spreadsheet

### ISSUE THREAD

**Issue by rlesiyon** [waldronlab/bugphyzz#251]
I am running into the issue of not able to open the google spreadsheet related used in [.importBacDiveExcel](https://github.com/waldronlab/bugphyzz/blob/8fc1c6df59efeacd5543fd187ac9ca7840dd3329/R/bacdive.R#L10)"

After cloning bugphyzzExports repository, and installing dependencies as describe in readme, and run this command in the bugphyzzExports directory

```{r}
Rscript inst/scripts/export_bugphyzz.R 
```
This is the error I get. 

```{r}
Warning: cannot open URL 'https://docs.google.com/spreadsheets/d/1smQTi1IKt4wSGTrGTW25I6u47M5txZkq/export?format=csv': HTTP status was '410 Gone'
Calls: system.time ... .importBacDiveExcel -> <Anonymous> -> read.table -> file
[1] "Error in file(file, \"rt\") : \n cannot open the connection to 'https://docs.google.com/spreadsheets/d/1smQTi1IKt4wSGTrGTW25I6u47M5txZkq/export?format=csv'\nCalls: system.time ... .importBacDiveExcel -> <Anonymous> -> read.table -> file\n"
```

and it traceback is as follows; 

```{r}
"Traceback:"
 "8: file(file, \"rt\")"                                                 
 "7: read.table(file = file, header = header, sep = sep, quote = quote, "
 "       dec = dec, fill = fill, comment.char = comment.char, ...)"      
 "6: utils::read.csv(url)"                                               
 "5: .importBacDiveExcel(verbose = verbose)"                             
 "4: .getBacDive(verbose = FALSE)"                                       
 "3: .reshapeBacDive(.getBacDive(verbose = FALSE))"                      
 "2: physiologies(phys_names, fullSource = FALSE)"                       
 "1: system.time({"                                                      
 "       phys <- physiologies(phys_names, fullSource = FALSE)"           
 "   })"                                         
```

Additionally if I access the [spreadsheet](https://docs.google.com/spreadsheets/d/1smQTi1IKt4wSGTrGTW25I6u47M5txZkq/export?format=csv) over the internet. I get this error 

![image (4)](https://github.com/user-attachments/assets/6ae43d2e-d535-4a24-ac42-aaeceba17ed2)

**Comment by sdgamboa** [comment]
@rlesiyon, thanks for opening this issue. I think this was solved in PR #252. I was wondering if you could try again.

**Comment by rlesiyon** [comment]
@sdgamboa, thanks. I am able to succesfully run the [bugphyzzExports](https://github.com/waldronlab/bugphyzzExports) export_bugphyzz script

**Comment by sdgamboa** [comment]
Thanks. Closing this issue.
