### ISSUE TITLE
A phylogenetic analysis looking for physiological patterns in clades

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#77]
Curtis Huttenhower had mentioned last year an idea about applying bugphyzz data to look for any interesting patterns in phylogenetic clades. Again, no clue how to proceed with this analysis--I'm sure Curtis's lab could help me out, if there are no takers.

just wanted to add this idea to the use case idea catalog :)

**Comment by lwaldron** [comment]
Examples of plotting attributes on a phylogenetic tree:
* https://www.molecularecologist.com/2017/02/08/phylogenetic-trees-in-r-using-ggtree/
* https://yulab-smu.top/treedata-book/chapter4.html

For our purposes probably better a taxonomic tree, ie try heat_tree:
* https://grunwaldlab.github.io/analysis_of_microbiome_community_data_in_r/05--plotting.html
